---

- name: Add backup interface
  template:
    src: usb.network.j2
    dest: /etc/systemd/network/br0.network
    force: yes
  notify:
    - Restart networkd

- name: Add BR0
  openvswitch_bridge:
    bridge: br0
    state: present

- name: Configure br0 interface
  template:
    src: br0.network.j2
    dest: /etc/systemd/network/br0.network
    force: yes

- name: Configure br0 physical interfaces
  template:
    src: "{{ item.interface }}.network.j2"
    dest: "/etc/systemd/network/mgmnt.network"
    force: yes
  loop: "{{ br0_interfaces }}"
  when: item.link == "present"
  notify:
    - Restart networkd

- name: Add ports to br0
  openvswitch_port:
    bridge: br0
    port: "{{ item.interface }}"
    state: "{{ item.link }}"
  loop: "{{ br0_interfaces }}"
  notify:
    - Restart networkd
