---

- name: Create systemd config
  template:
    src: "{{ docker_100.name }}.network.j2"
    dest: "/etc/systemd/network/{{ docker_100.name }}.network"
    force: yes
  notify:
    - Restart networkd

- name: Create Docker network
  docker_network:
    name: "{{ docker_100.name }}"
    ipam_config:
      - subnet: "{{ docker_100.subnet }}"
        gateway: "{{ docker_100.gateway }}"
    driver_options:
      com.docker.network.bridge.name: "{{ docker_100.name }}"
