---
#From Github
- src: https://www.github.com/mrlesmithjr/ansible-nodejs.git
- src: https://www.github.com/mrlesmithjr/ansible-netdata.git
- src: https://github.com/stackhpc/ansible-role-libvirt-vm.git

#From Galaxy
