stages:
    - predeploy
    - bootstrap

image: registry.gitlab.com/torese/docker-ansible

variables:
    ANSIBLE_HOST_KEY_CHECKING: 'false'
    ANSIBLE_FORCE_COLOR: 'true'

predeploy:
    stage: predeploy
    script:
      - cd nuc-client
      - ansible -i hosts all -m ping --extra-vars "ansible_password=${ANSIBLE_SSHKEY}" 

configure_hosts:
    stage: bootstrap
    allow_failure: false
    script:
        - cd nuc-client
        - ansible-playbook main.yml -i hosts --extra-vars "ansible_become_pass=${ANSIBLE_SSHKEY} ansible_password=${ANSIBLE_SSHKEY}"