workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web"'
      when: always  # Trigger pipeline only from web
    - when: never # For other cases, don't trigger

stages:
    - predeploy
    - deploy

image: registry.gitlab.com/torese/docker-ansible

variables:
    ANSIBLE_HOST_KEY_CHECKING: 'false'
    ANSIBLE_FORCE_COLOR: 'true'

predeploy:
    stage: predeploy
    script:
      - cd nuc-client
      - ansible -i hosts ${TARGET} -m ping --extra-vars "ansible_password=${ANSIBLE_SSHKEY}" 

configure_hosts:
    stage: deploy
    allow_failure: false
    script:
        - cd nuc-client
        - ansible-playbook ${PLAYBOOK} -i hosts --extra-vars "target=${TARGET} ansible_become_pass=${ANSIBLE_SSHKEY} ansible_password=${ANSIBLE_SSHKEY}"
