- repo: https://github.com/ansible/ansible-lint.git
  sha: v4.1.0
  hooks:
    - id: ansible-lint
      files: \.(yaml|yml)$
- repo: https://github.com/adrienverge/yamllint.git
  sha: v1.15.0
  hooks:
    - id: yamllint
      args: [-c=.yaml-lint]
