---

host_interface: enp2s0
br0_interfaces:
  - interface: enp2s0
    link: present

vlan:
  - name: "100"
    id: "100"
    network: 10.100.0.0
    address: 10.100.0.100
    mask: 24
    gateway: 10.100.0.1

docker_100:
  name: docker-100
  network: 172.18.0.0
  mask: 24
  subnet: 172.18.0.0/24
  gateway: 172.18.0.1

docker_pihole_100:
  name: pihole_{{ vlan.0.name }}
  image: "pihole/pihole:latest"
  dns:
    - "127.0.0.1"
    - "9.9.9.9"
  timezone: "America/Los_Angeles"
  password: "{{ web_passwd }}"
  volumes:
    - "{{ ansible_env.HOME }}/etc/pihole-{{ vlan.0.name }}:/etc/pihole/"
    - "{{ ansible_env.HOME }}/etc/dnsmasq-d{{ vlan.0.name }}:/etc/dnsmasq.d/"
    - "{{ ansible_env.HOME }}/etc/overwrite_resolv.conf:/etc/resolv.conf"

  networks: "{{ docker_100.name }}"
  ports:
    - "{{ vlan.0.address }}:53:53/tcp"
    - "{{ vlan.0.address }}:53:53/udp"
    - "{{ vlan.0.address }}:80:80/tcp"
    - "{{ vlan.0.address }}:443:443/tcp"
  server_ip: "{{ vlan.0.address }}"
