---
# tasks file for roles/restore-vm
- import_role:
    name: kvm-vms
    tasks_from: nfv-vm1
  vars:
    restore_nfv_vm1: True
  tags: ['never', 'restore-nfv-vm1']

- import_role:
    name: kvm-vms
    tasks_from: nfv-controller
  vars:
    restore_nfv_controller: True
  tags: ['never', 'restore-nfv-controller']


- import_role:
    name: kvm-vms
    tasks_from: eve-ng
  vars:
    restore_eve: True
  tags: ['never', 'restore-eve-ng']
