---

- hosts: '{{ target }}'
  gather_facts: true
  become: true
  vars:
    work_dir: "/home/dockeruser/homeassistant"
    docker_user: dockeruser
    docker_group: dockergroup  
  tasks:

    - name: Ensure the service config directory is present
      file:
        path: "{{ work_dir }}"
        owner: "{{ docker_user }}"
        group: "{{ docker_group }}"
        state: directory
        mode: 0755
    
    - name: Get id of user
      shell: "id -u {{ docker_user }}"
      register: user_id
      failed_when: user_id.rc != 0

    - name: Get id of group
      shell: "getent group {{ docker_group }} | cut -d: -f3"
      register: group_id
      failed_when: group_id.stdout | length == 0

    - name: Container present
      docker_container:
        name: mycontainer
        state: started
        image: alpine
        user: "{{ user_id.stdout }}:{{ group_id.stdout }}"
        command: sleep infinity