---
- name: Stop VM is running
  virt:
    name: nfv-vm1
    command: shutdown

- name: Make sure VM is stopped
  virt:
    name: nfv-vm1
    command: status
  register: task_result
  ignore_errors: yes
  retries: 10
  until: task_result['status'] == 'shutdown'
  delay: 1

- name: Destroy VM if failed to stop
  virt:
    name: nfv-vm1
    command: destroy
  when: task_result['failed']

- name: Create Snapshot
  shell: qemu-img snapshot -c backup-nfv-vm1 nfvvm1-vol1
  args:
    chdir: '{{ libvirt_image_dir }}'

- name: Create Snapshot Qcow2
  shell: 'qemu-img convert -f qcow2 -O qcow2 -s backup-nfv-vm1 nfvvm1-vol1 {{ backup_dir }}/backup-nfv-vm1.qcow2'
  args:
    chdir: '{{ libvirt_image_dir }}'

- name: Delete Snapshot
  shell: qemu-img snapshot -d backup-nfv-vm1 nfvvm1-vol1
  args:
    chdir: '{{ libvirt_image_dir }}'

- name: Start the VM
  virt:
    name: nfv-vm1
    command: start
