---

- name: "Setup the pi-hole docker container"
  docker_container:
    name: "{{ docker_pihole.name }}"
    image: "{{ docker_pihole.image }}"
    pull: "yes"
    state: "{{ docker_pihole.state | default('started') }}"
    restart: "{{ docker_pihole.restart }}"
    restart_policy: "{{ docker_pihole.restart_policy | default('unless-stopped') }}"
    networks_cli_compatible: true
    networks: "{{ docker_pihole.networks }}"
    volumes: "{{ docker_pihole.volumes }}"
    env:
      TZ: "{{ docker_pihole.env.timezone }}"
      WEBPASSWORD: "{{ docker_pihole.env.password }}"
      ServerIP: "{{ docker_pihole.env.server_ip }}"
      DNS1: "{{ docker_pihole.env.dns1 }}"
      DNS2: "{{ docker_pihole.env.dns2 | default('no') }}"
    capabilities: NET_ADMIN
    dns_servers:
      - "127.0.0.1"
    ports: "{{ docker_pihole.ports }}"
    healthcheck:
      test: "dig +retry=0 @{{ docker_pihole.env.server_ip }} pi.hole || exit 1"
