---

- name: Ensures {{ ansible_env.HOME }}/etc/ dir exists
  file:
    path: "{{ ansible_env.HOME }}/etc/"
    state: directory

- name: Overwrite Resolv.conf
  copy:
    content: "nameserver 127.0.0.1\nnameserver 10.100.0.1\n"
    dest: "{{ ansible_env.HOME }}/etc/overwrite_resolv.conf"
    force: true

- name: Spin up pihole
  import_tasks: pihole_base.yml
  vars:
    docker_pihole:
      name: "{{ docker_pihole_100.name }}"
      image: "{{ docker_pihole_100.image }}"
      restart: true
      networks:
        - name: "{{ docker_pihole_100.networks }}"
      volumes: "{{ docker_pihole_100.volumes }}"
      env:
        timezone: "{{ docker_pihole_100.timezone }}"
        password: "{{ docker_pihole_100.password }}"
        server_ip: "{{ docker_pihole_100.server_ip }}"
        dns1: 54.183.15.10
      ports: "{{ docker_pihole_100.ports }}"

- name: Modify FTL.conf for custom settings
  copy:
    content: "RESOLVE_IPV6=no\n"
    dest: "{{ ansible_env.HOME }}/etc/pihole-{{ vlan.0.name }}/pihole-FTL.conf"
    force: true

- name: Custom DNS for domains
  copy:
    content: "max-ttl=15\nmax-cache-ttl=15\nserver=/crashlytics.com/208.67.222.222\n"
    dest: "{{ ansible_env.HOME }}/etc/dnsmasq-d{{ vlan.0.name }}/02-mydomain.conf"
    force: true
