---

- name: Printing the environment​ variable in Ansible
  set_fact:
    user_home: "{{ lookup('env','HOME') }}"

- name: Set up Smokeping docker
  docker_container:
    name: "smokeping_100"
    image: "linuxserver/smokeping"
    state: "started"
    restart: true
    restart_policy: "unless-stopped"
    networks_cli_compatible: true
    networks:
      - name: "{{ docker_100.name }}"
    ports:
      - "{{ vlan.0.address }}:8080:80/tcp"
    env:
      TZ: "America/Los_Angeles"
      PUID: "1000"
      PGID: "1000"
    volumes:
      - "{{ user_home }}/smokeping_100/config:/config"
      - "{{ user_home }}/smokeping_100/data:/data"
    dns_servers:
      - "{{ vlan.0.gateway }}"
